name: Compile Cloudflare DNS Manager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_linux:
    name: Build for Linux AMD64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Nuitka and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt

    - name: Compile with Nuitka for Linux
      run: |
        python -m nuitka --standalone --onefile --output-dir=./build_linux main.py \
          --enable-plugin=tk-inter \
          --include-data-files=cloudflare-dns-manager.png=.

    - name: Upload Linux compiled executable
      uses: actions/upload-artifact@v4
      with:
        name: cloudflare-dns-manager-linux-amd64
        path: ./build_linux/main.dist/*

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_linux]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Download compiled artifact
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./artifacts/cloudflare-dns-manager-linux-amd64/*
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          Cloudflare DNS Manager Release for ${{ github.ref_name }}
          
          This release includes:
          - Linux AMD64 executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}